repos:
  - repo: https://github.com/lietu/go-pre-commit
    rev: v1.0.0
    hooks:
      - id: errcheck
      - id: go-fmt-goimports
      - id: go-test
      - id: go-vet
      - id: gofumpt
      - id: golint
      - id: staticcheck
      - id: go-mod-tidy
