repos:
  - repo: https://github.com/lietu/go-pre-commit
    rev: v1.0.0
    hooks:
      - id: errcheck
      - id: go-fmt-goimports
      - id: go-test
      - id: go-vet
      - id: gofumpt
      - id: golangci-lint
      - id: golint
      - id: staticcheck
      - id: go-mod-tidy
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.6.1
    hooks:
      - id: golangci-lint
        args: ["run", "--fix"]
